name: funance
version: 1.0.0
config-version: 2

profile: funance

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"


models:
  funance:
    staging_funance:
      materialized: table
      +schema: staging_funance
    dwh_funance:
      materialized: table
      +schema: dwh_funance